name: 'Register Events with Devenv'
description: 'Send Github event details to Devenv'
inputs:
  devenv-api-url:  # id of input
    description: 'Devenv API Endpoint'
    required: true
  devenv-client-secret-key-id:  # id of input
    description: 'client secret key id obtained for Devenv access'
    required: true
  devenv-client-secret-key:  # id of input
    description: 'client secret key obtained for Devenv access'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'