on: [push]

jobs:
  register_event_job:
    runs-on: ubuntu-latest
    name: A job to register github events with Devenv
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Register Github events with Devenv
        uses: ./
        id: register_events
        with:
          devenv-api-url: ${{ secrets.devenv_api }}
          devenv-client-secret-key-id: ${{ secrets.devenv_secret_key_id }}
          devenv-client-secret-key: ${{ secrets.devenv_secret_key }}